name: Build
on: [push]
jobs:
  gradle-build:
    runs-on: ubuntu-latest
    env:
      JDK_VERSION: 11
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew build
